version: "3"
services:
  api:
    build: .
    ports:
      - 4000:8000
    environment:
      - DATABASE_HOSTNAME=postgres # resolve to the current network
      - DATABASE_PORT=5433
      - DATABASE_PASSWORD=Johanna12.
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=JEDUGVFCHNHGVNDNRIHNVDFVNRHVDIDHCIi8r84jemdndm
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Johanna12.
      - POSTGRES_DB=fastapi
      - POSTGRES_HOST_AUTH_METHOD=trust

    volumes:
      - postgres-db:/var/lib/postresql/data

volumes:
  postgres-db:

